language: node_js
node_js:
- '7'
cache:
  - yarn
deploy:
  provider: heroku
  api_key:
    secure: LA/txrtqHiEoX2zd5Y24eF2/VZCYX51iZj9Z6n1CUwBxzuRgy8EmVVancmzq1JOnVWdmDq8UTIKFGV7rgAN6H0xGnIAbPy834s56IZuLKKGIUjk+MZ4E2DEURt4NB4yBhfukd5uVzMnJ80xaO9pe26fHLtRKmDVnr+d7qq/QnbCOui5ztorJ0qhyruMn7HkIWmSyNR2dhGVfLhlg6NDd+l7K3W8x/SygHD92UdJMYiAc563Yj3TaQVt4onpnKx2U5B89n1av7blR4hmRfNqHpXjAESgcKE7XTr6h4wTU0SkSkJliT5xO49YVIqb2CYNzY8E/6ozV8cda5oayXeF2qemjTRBvIc0iorBvW5+yaiMvbTQnoJ7slArxyQiEbTKJ7uuqPHpDDOUgN/YawWhhjD99FSRW7biD+sGIJ2tAKsfiHP+Cg7EK9d10TMMEj6604HDlV+oCTuKOs3IYAs0fTw+CY4yl02fELE6TmKgcGYZNu9Hz9H415ZWmZGcDpRkY13YHmRuuAEPqzQJDntfjVhgfN5MvXdYfkYsw37WIX5muS/PHHoubYiQ0jM0TJYyspz2ZlEHNAU0yxy3HDeu08/yNqm6XdiWCbtx5s+jhUjXeFtPXJPvDVYU2VEEb47tlEs3xZiHI+MtqKKeAIp8o7eAzhzeFtiMzM+Ld+4wL8QE=
  app: ryantg
  on:
    repo: protoEvangelium/MERN-Portfolio
